const brandsData = [
    { name: "Maruti Suzuki", logo: "assets/images/brands/maruti.png" },
    { name: "Hyundai", logo: "assets/images/brands/hyundai.png" },
    { name: "Tata", logo: "assets/images/brands/tata.png" },
    { name: "Mahindra", logo: "assets/images/brands/mahindra.png" },
    { name: "Toyota", logo: "assets/images/brands/toyota.png" },
    { name: "Honda", logo: "assets/images/brands/honda.png" },
    { name: "Kia", logo: "assets/images/brands/kia.png" },
    { name: "MG", logo: "assets/images/brands/mg.png" },
    { name: "Skoda", logo: "assets/images/brands/skoda.png" },
    { name: "Volkswagen", logo: "assets/images/brands/vw.png" },
    { name: "Nissan", logo: "assets/images/brands/nissan.svg" },
    { name: "Renault", logo: "assets/images/brands/renault.svg" },
    { name: "BMW", logo: "assets/images/brands/bmw.png" },
    { name: "Audi", logo: "assets/images/brands/audi.png" },
    { name: "Mercedes-Benz", logo: "assets/images/brands/benz.png" }
];

const modelsData = {
    "Maruti Suzuki": ["Alto K10", "Baleno", "Brezza", "Dzire", "Ertiga", "Fronx", "Grand Vitara", "Swift", "Wagon R"],
    "Hyundai": ["Alcazar", "Creta", "Grand i10 Nios", "i20", "Venue", "Verna"],
    "Tata": ["Altroz", "Harrier", "Nexon", "Punch", "Safari", "Tiago"],
    "Mahindra": ["Bolero Neo", "Scorpio N", "Thar", "XUV300", "XUV700"],
    "Toyota": ["Fortuner", "Glanza", "Urban Cruiser Hyryder", "Innova Hycross"],
    "Honda": ["Amaze", "City", "Elevate"],
    "Kia": ["Carens", "EV6", "Seltos", "Sonet"],
    "MG": ["Astor", "Hector"],
    "Skoda": ["Kushaq", "Slavia"],
    "Volkswagen": ["Taigun", "Virtus"],
    "Nissan": ["Magnite"],
    "Renault": ["Kiger", "Kwid", "Triber"],
    "BMW": ["3 Series Gran Limousine"],
    "Audi": ["A4"],
    "Mercedes-Benz": ["C-Class"]
};

const carsData = [
    {
        "id": 1,
        "brand": "Honda",
        "model": "Amaze",
        "year": 2024,
        "variant": "VX CVT",
        "formatted_price": "₹9.35 Lakh",
        "emi": "₹19,500",
        "mileage": "18.3 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Sedan",
        "engine": "1199 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/amaze/1.png",
            "assets/images/amaze/2.png",
            "assets/images/amaze/3.jpeg",
            "assets/images/amaze/4.jpeg"
        ]
    },
    {
        "id": 2,
        "brand": "Honda",
        "model": "City",
        "year": 2024,
        "variant": "ZX CVT",
        "formatted_price": "₹16.30 Lakh",
        "emi": "₹34,000",
        "mileage": "18.4 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Sedan",
        "engine": "1498 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/city/1.jpg",
            "assets/images/city/2.jpg",
            "assets/images/city/3.jpg",
            "assets/images/city/4.jpg"
        ]
    },
    {
        "id": 3,
        "brand": "Honda",
        "model": "Elevate",
        "year": 2024,
        "variant": "ZX CVT",
        "formatted_price": "₹16.20 Lakh",
        "emi": "₹33,800",
        "mileage": "16.92 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1498 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/elevate/1.png",
            "assets/images/elevate/2.png",
            "assets/images/elevate/3.jpeg",
            "assets/images/elevate/4.jpeg"
        ]
    },
    {
        "id": 4,
        "brand": "Hyundai",
        "model": "Alcazar",
        "year": 2024,
        "variant": "Signature (O)",
        "formatted_price": "₹21.23 Lakh",
        "emi": "₹44,500",
        "mileage": "18.1 kmpl",
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1493 cc",
        "seating_capacity": 7,
        "seats": 7,
        "featured": false,
        "images": [
            "assets/images/alcazar/1.png",
            "assets/images/alcazar/2.png",
            "assets/images/alcazar/3.png",
            "assets/images/alcazar/4.jpeg"
        ]
    },
    {
        "id": 5,
        "brand": "Hyundai",
        "model": "Creta",
        "year": 2024,
        "variant": "SX (O)",
        "formatted_price": "₹19.24 Lakh",
        "emi": "₹40,200",
        "mileage": "18.4 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1497 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": true,
        "images": [
            "assets/images/creta/1.png",
            "assets/images/creta/2.png",
            "assets/images/creta/3.jpg",
            "assets/images/creta/4.jpg"
        ]
    },
    {
        "id": 6,
        "brand": "Hyundai",
        "model": "Grand i10 Nios",
        "year": 2024,
        "variant": "Asta AMT",
        "formatted_price": "₹8.51 Lakh",
        "emi": "₹17,800",
        "mileage": "20.7 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Hatchback",
        "engine": "1197 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/grand-i10-nios/1.png",
            "assets/images/grand-i10-nios/2.png",
            "assets/images/grand-i10-nios/3.png",
            "assets/images/grand-i10-nios/4.jpeg"
        ]
    },
    {
        "id": 7,
        "brand": "Hyundai",
        "model": "i20",
        "year": 2024,
        "variant": "Asta (O) CVT",
        "formatted_price": "₹11.01 Lakh",
        "emi": "₹23,000",
        "mileage": "19.65 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Hatchback",
        "engine": "1197 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/i20/1.png",
            "assets/images/i20/2.png",
            "assets/images/i20/3.jpeg",
            "assets/images/i20/4.jpeg"
        ]
    },
    {
        "id": 8,
        "brand": "Hyundai",
        "model": "Venue",
        "year": 2024,
        "variant": "SX (O) DCT",
        "formatted_price": "₹13.48 Lakh",
        "emi": "₹28,200",
        "mileage": "18.15 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "998 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/venue/1.jpeg",
            "assets/images/venue/2.jpeg",
            "assets/images/venue/3.jpeg",
            "assets/images/venue/4.jpeg"
        ]
    },
    {
        "id": 9,
        "brand": "Hyundai",
        "model": "Verna",
        "year": 2024,
        "variant": "SX (O) Turbo DCT",
        "formatted_price": "₹17.38 Lakh",
        "emi": "₹36,300",
        "mileage": "20.6 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Sedan",
        "engine": "1482 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/verna/1.png",
            "assets/images/verna/2.png",
            "assets/images/verna/3.jpeg",
            "assets/images/verna/4.jpeg"
        ]
    },
    {
        "id": 10,
        "brand": "Kia",
        "model": "Carens",
        "year": 2024,
        "variant": "Luxury Plus",
        "formatted_price": "₹18.95 Lakh",
        "emi": "₹39,600",
        "mileage": "16.2 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "MUV",
        "engine": "1482 cc",
        "seating_capacity": 7,
        "seats": 7,
        "featured": false,
        "images": [
            "assets/images/carens/1.png",
            "assets/images/carens/2.png",
            "assets/images/carens/3.jpeg",
            "assets/images/carens/4.jpeg"
        ]
    },
    {
        "id": 11,
        "brand": "Kia",
        "model": "EV6",
        "year": 2024,
        "variant": "GT Line AWD",
        "formatted_price": "₹65.95 Lakh",
        "emi": "₹1,38,000",
        "mileage": "708 km/charge",
        "fuel_type": "Electric",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "N/A",
        "seating_capacity": 5,
        "seats": 5,
        "featured": true,
        "images": [
            "assets/images/ev6/1.png",
            "assets/images/ev6/2.png",
            "assets/images/ev6/3.jpeg",
            "assets/images/ev6/4.jpeg"
        ]
    },
    {
        "id": 12,
        "brand": "Kia",
        "model": "Seltos",
        "year": 2024,
        "variant": "X-Line",
        "formatted_price": "₹20.30 Lakh",
        "emi": "₹42,500",
        "mileage": "17.7 kmpl",
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1493 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/seltos/1.jpg",
            "assets/images/seltos/2.jpg",
            "assets/images/seltos/3.jpg",
            "assets/images/seltos/4.jpg"
        ]
    },
    {
        "id": 13,
        "brand": "Kia",
        "model": "Sonet",
        "year": 2024,
        "variant": "X-Line DCT",
        "formatted_price": "₹14.75 Lakh",
        "emi": "₹30,800",
        "mileage": "18.3 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "998 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/sonet/1.png",
            "assets/images/sonet/2.png",
            "assets/images/sonet/3.png",
            "assets/images/sonet/4.jpeg"
        ]
    },
    {
        "id": 14,
        "brand": "Mahindra",
        "model": "Bolero Neo",
        "year": 2024,
        "variant": "N10",
        "formatted_price": "₹11.47 Lakh",
        "emi": "₹24,000",
        "mileage": "17.2 kmpl",
        "fuel_type": "Diesel",
        "transmission": "Manual",
        "body_type": "SUV",
        "engine": "1493 cc",
        "seating_capacity": 7,
        "seats": 7,
        "featured": false,
        "images": [
            "assets/images/bolero-neo/1.png",
            "assets/images/bolero-neo/2.png",
            "assets/images/bolero-neo/3.jpeg",
            "assets/images/bolero-neo/4.jpeg"
        ]
    },
    {
        "id": 15,
        "brand": "Mahindra",
        "model": "Scorpio N",
        "year": 2024,
        "variant": "Z8 L",
        "formatted_price": "₹24.05 Lakh",
        "emi": "₹50,300",
        "mileage": "13.2 kmpl",
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "2184 cc",
        "seating_capacity": 7,
        "seats": 7,
        "featured": true,
        "images": [
            "assets/images/scorpio-n/1.jpeg",
            "assets/images/scorpio-n/2.jpeg",
            "assets/images/scorpio-n/3.jpeg",
            "assets/images/scorpio-n/4.jpeg"
        ]
    },
    {
        "id": 16,
        "brand": "Mahindra",
        "model": "Thar",
        "year": 2024,
        "variant": "LX 4-Str Hard Top",
        "formatted_price": "₹16.94 Lakh",
        "emi": "₹35,400",
        "mileage": "15.2 kmpl",
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "2184 cc",
        "seating_capacity": 4,
        "seats": 4,
        "featured": false,
        "images": [
            "assets/images/thar/1.png",
            "assets/images/thar/2.png",
            "assets/images/thar/3.png",
            "assets/images/thar/4.jpeg"
        ]
    },
    {
        "id": 17,
        "brand": "Mahindra",
        "model": "XUV300",
        "year": 2024,
        "variant": "W8 Opt AMT",
        "formatted_price": "₹14.75 Lakh",
        "emi": "₹30,800",
        "mileage": "19.7 kmpl",
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1497 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/xuv300/1.jpeg",
            "assets/images/xuv300/2.jpeg",
            "assets/images/xuv300/3.jpeg",
            "assets/images/xuv300/4.jpeg"
        ]
    },
    {
        "id": 18,
        "brand": "Mahindra",
        "model": "XUV700",
        "year": 2024,
        "variant": "AX7 Luxury Pack",
        "formatted_price": "₹26.99 Lakh",
        "emi": "₹56,400",
        "mileage": "13 kmpl",
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "2184 cc",
        "seating_capacity": 7,
        "seats": 7,
        "featured": false,
        "images": [
            "assets/images/xuv700/1.jpeg",
            "assets/images/xuv700/2.jpeg",
            "assets/images/xuv700/3.jpeg",
            "assets/images/xuv700/4.jpeg"
        ]
    },
    {
        "id": 19,
        "brand": "Maruti Suzuki",
        "model": "Alto K10",
        "year": 2024,
        "variant": "VXi Plus",
        "formatted_price": "₹5.35 Lakh",
        "emi": "₹11,200",
        "mileage": "24.39 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Manual",
        "body_type": "Hatchback",
        "engine": "998 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/alto-k10/1.png",
            "assets/images/alto-k10/2.png",
            "assets/images/alto-k10/3.jpeg",
            "assets/images/alto-k10/4.jpeg"
        ]
    },
    {
        "id": 20,
        "brand": "Maruti Suzuki",
        "model": "Baleno",
        "year": 2024,
        "variant": "Alpha AMT",
        "formatted_price": "₹9.88 Lakh",
        "emi": "₹20,600",
        "mileage": "22.94 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Hatchback",
        "engine": "1197 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/baleno/1.jpeg",
            "assets/images/baleno/2.jpeg",
            "assets/images/baleno/3.jpeg",
            "assets/images/baleno/4.jpeg"
        ]
    },
    {
        "id": 21,
        "brand": "Maruti Suzuki",
        "model": "Brezza",
        "year": 2024,
        "variant": "ZXi Plus AT",
        "formatted_price": "₹13.98 Lakh",
        "emi": "₹29,200",
        "mileage": "19.8 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1462 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": true,
        "images": [
            "assets/images/brezza/1.png",
            "assets/images/brezza/2.png",
            "assets/images/brezza/3.jpeg",
            "assets/images/brezza/4.jpeg"
        ]
    },
    {
        "id": 22,
        "brand": "Maruti Suzuki",
        "model": "Dzire",
        "year": 2024,
        "variant": "ZXi Plus AGS",
        "formatted_price": "₹9.39 Lakh",
        "emi": "₹19,600",
        "mileage": "22.61 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Sedan",
        "engine": "1197 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/dzire/1.png",
            "assets/images/dzire/2.png",
            "assets/images/dzire/3.jpeg",
            "assets/images/dzire/4.jpeg"
        ]
    },
    {
        "id": 23,
        "brand": "Maruti Suzuki",
        "model": "Ertiga",
        "year": 2024,
        "variant": "ZXi Plus AT",
        "formatted_price": "₹13.08 Lakh",
        "emi": "₹27,300",
        "mileage": "20.3 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "MUV",
        "engine": "1462 cc",
        "seating_capacity": 7,
        "seats": 7,
        "featured": false,
        "images": [
            "assets/images/ertiga/1.png",
            "assets/images/ertiga/2.png",
            "assets/images/ertiga/3.jpeg",
            "assets/images/ertiga/4.jpeg"
        ]
    },
    {
        "id": 24,
        "brand": "Maruti Suzuki",
        "model": "Fronx",
        "year": 2024,
        "variant": "Alpha Turbo AT",
        "formatted_price": "₹13.04 Lakh",
        "emi": "₹27,200",
        "mileage": "20.01 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "998 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/fronx/1.jpeg",
            "assets/images/fronx/2.jpeg",
            "assets/images/fronx/3.jpeg",
            "assets/images/fronx/4.jpeg"
        ]
    },
    {
        "id": 25,
        "brand": "Maruti Suzuki",
        "model": "Grand Vitara",
        "year": 2024,
        "variant": "Alpha Plus Hybrid",
        "formatted_price": "₹19.93 Lakh",
        "emi": "₹41,700",
        "mileage": "27.97 kmpl",
        "fuel_type": "Hybrid",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1490 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/grand-vitara/1.png",
            "assets/images/grand-vitara/2.png",
            "assets/images/grand-vitara/3.jpeg",
            "assets/images/grand-vitara/4.jpeg"
        ]
    },
    {
        "id": 26,
        "brand": "Maruti Suzuki",
        "model": "Swift",
        "year": 2024,
        "variant": "ZXi Plus AMT",
        "formatted_price": "₹8.99 Lakh",
        "emi": "₹18,800",
        "mileage": "22.56 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Hatchback",
        "engine": "1197 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": true,
        "images": [
            "assets/images/swift/1.jpg",
            "assets/images/swift/2.jpg",
            "assets/images/swift/3.jpg",
            "assets/images/swift/4.jpg"
        ]
    },
    {
        "id": 27,
        "brand": "Maruti Suzuki",
        "model": "Wagon R",
        "year": 2024,
        "variant": "ZXi Plus AGS",
        "formatted_price": "₹7.30 Lakh",
        "emi": "₹15,200",
        "mileage": "24.43 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Hatchback",
        "engine": "1197 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/wagon-r/1.jpeg",
            "assets/images/wagon-r/2.png",
            "assets/images/wagon-r/3.jpeg",
            "assets/images/wagon-r/4.jpeg"
        ]
    },
    {
        "id": 28,
        "brand": "MG",
        "model": "Astor",
        "year": 2024,
        "variant": "Savvy Turbo AT",
        "formatted_price": "₹17.90 Lakh",
        "emi": "₹37,400",
        "mileage": "14.3 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1349 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/astor/1.png",
            "assets/images/astor/2.png",
            "assets/images/astor/3.png",
            "assets/images/astor/4.jpeg"
        ]
    },
    {
        "id": 29,
        "brand": "MG",
        "model": "Hector",
        "year": 2024,
        "variant": "Savvy Pro",
        "formatted_price": "₹22.15 Lakh",
        "emi": "₹46,300",
        "mileage": "12.0 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1451 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/hector/1.png",
            "assets/images/hector/2.png",
            "assets/images/hector/3.jpeg",
            "assets/images/hector/4.jpeg"
        ]
    },
    {
        "id": 30,
        "brand": "Nissan",
        "model": "Magnite",
        "year": 2024,
        "variant": "XV Premium Turbo CVT",
        "formatted_price": "₹11.11 Lakh",
        "emi": "₹23,200",
        "mileage": "17.4 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "999 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/magnite/1.png",
            "assets/images/magnite/2.png",
            "assets/images/magnite/3.jpeg",
            "assets/images/magnite/4.jpeg"
        ]
    },
    {
        "id": 31,
        "brand": "Renault",
        "model": "Kiger",
        "year": 2024,
        "variant": "RXZ Turbo CVT",
        "formatted_price": "₹11.23 Lakh",
        "emi": "₹23,400",
        "mileage": "18.24 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "999 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/kiger/1.png",
            "assets/images/kiger/2.png",
            "assets/images/kiger/3.png",
            "assets/images/kiger/4.jpeg"
        ]
    },
    {
        "id": 32,
        "brand": "Renault",
        "model": "Kwid",
        "year": 2024,
        "variant": "Climber AMT",
        "formatted_price": "₹6.33 Lakh",
        "emi": "₹13,200",
        "mileage": "22.3 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Hatchback",
        "engine": "999 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/kwid/1.png",
            "assets/images/kwid/2.png",
            "assets/images/kwid/3.jpeg",
            "assets/images/kwid/4.jpeg"
        ]
    },
    {
        "id": 33,
        "brand": "Renault",
        "model": "Triber",
        "year": 2024,
        "variant": "RXZ EASY-R",
        "formatted_price": "₹8.97 Lakh",
        "emi": "₹18,700",
        "mileage": "18.2 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "MUV",
        "engine": "999 cc",
        "seating_capacity": 7,
        "seats": 7,
        "featured": false,
        "images": [
            "assets/images/triber/1.png",
            "assets/images/triber/2.png",
            "assets/images/triber/3.jpeg",
            "assets/images/triber/4.jpeg"
        ]
    },
    {
        "id": 34,
        "brand": "Skoda",
        "model": "Kushaq",
        "year": 2024,
        "variant": "Style 1.5 DSG",
        "formatted_price": "₹19.69 Lakh",
        "emi": "₹41,200",
        "mileage": "18.86 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1498 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/kushaq/1.png",
            "assets/images/kushaq/2.png",
            "assets/images/kushaq/3.png",
            "assets/images/kushaq/4.jpeg"
        ]
    },
    {
        "id": 35,
        "brand": "Skoda",
        "model": "Slavia",
        "year": 2024,
        "variant": "Style 1.5 DSG",
        "formatted_price": "₹18.92 Lakh",
        "emi": "₹39,500",
        "mileage": "19.47 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Sedan",
        "engine": "1498 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/slavia/1.png",
            "assets/images/slavia/2.png",
            "assets/images/slavia/3.jpeg",
            "assets/images/slavia/4.jpeg"
        ]
    },
    {
        "id": 36,
        "brand": "Tata",
        "model": "Altroz",
        "year": 2024,
        "variant": "XZ Plus DCA",
        "formatted_price": "₹10.74 Lakh",
        "emi": "₹22,400",
        "mileage": "18.5 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Hatchback",
        "engine": "1199 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/altroz/1.png",
            "assets/images/altroz/2.png",
            "assets/images/altroz/3.jpeg",
            "assets/images/altroz/4.jpeg"
        ]
    },
    {
        "id": 37,
        "brand": "Tata",
        "model": "Harrier",
        "year": 2024,
        "variant": "Fearless Plus Dark AT",
        "formatted_price": "₹26.44 Lakh",
        "emi": "₹55,300",
        "mileage": "14.6 kmpl",
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1956 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": true,
        "images": [
            "assets/images/harrier/1.png",
            "assets/images/harrier/2.png",
            "assets/images/harrier/3.jpeg",
            "assets/images/harrier/4.jpeg"
        ]
    },
    {
        "id": 38,
        "brand": "Tata",
        "model": "Nexon",
        "year": 2024,
        "variant": "Fearless Plus S",
        "formatted_price": "₹14.79 Lakh",
        "emi": "₹30,900",
        "mileage": "17.01 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1199 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/nexon/1.jpeg",
            "assets/images/nexon/2.png",
            "assets/images/nexon/3.png",
            "assets/images/nexon/4.jpeg"
        ]
    },
    {
        "id": 39,
        "brand": "Tata",
        "model": "Punch",
        "year": 2024,
        "variant": "Creative Flagship AMT",
        "formatted_price": "₹10.10 Lakh",
        "emi": "₹21,100",
        "mileage": "18.8 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1199 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/punch/1.png",
            "assets/images/punch/2.jpeg",
            "assets/images/punch/3.jpeg",
            "assets/images/punch/4.jpeg"
        ]
    },
    {
        "id": 40,
        "brand": "Tata",
        "model": "Safari",
        "year": 2024,
        "variant": "Accomplished Plus Dark AT",
        "formatted_price": "₹27.34 Lakh",
        "emi": "₹57,100",
        "mileage": "14.08 kmpl",
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1956 cc",
        "seating_capacity": 7,
        "seats": 7,
        "featured": false,
        "images": [
            "assets/images/safari/1.png",
            "assets/images/safari/2.png",
            "assets/images/safari/3.jpeg",
            "assets/images/safari/4.jpeg"
        ]
    },
    {
        "id": 41,
        "brand": "Tata",
        "model": "Tiago",
        "year": 2024,
        "variant": "XZA Plus",
        "formatted_price": "₹7.80 Lakh",
        "emi": "₹16,300",
        "mileage": "19.0 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Hatchback",
        "engine": "1199 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/tiago/1.png",
            "assets/images/tiago/2.png",
            "assets/images/tiago/3.png",
            "assets/images/tiago/4.jpeg"
        ]
    },
    {
        "id": 42,
        "brand": "Toyota",
        "model": "Fortuner",
        "year": 2024,
        "variant": "GR-S",
        "formatted_price": "₹51.44 Lakh",
        "emi": "₹1,07,500",
        "mileage": "10.0 kmpl",
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "2755 cc",
        "seating_capacity": 7,
        "seats": 7,
        "featured": true,
        "images": [
            "assets/images/fortuner/1.jpg",
            "assets/images/fortuner/2.jpg",
            "assets/images/fortuner/3.jpg",
            "assets/images/fortuner/4.jpg"
        ]
    },
    {
        "id": 43,
        "brand": "Toyota",
        "model": "Glanza",
        "year": 2024,
        "variant": "V AMT",
        "formatted_price": "₹10.00 Lakh",
        "emi": "₹20,900",
        "mileage": "22.94 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Hatchback",
        "engine": "1197 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/glanza/1.png",
            "assets/images/glanza/2.png",
            "assets/images/glanza/3.png",
            "assets/images/glanza/4.jpeg"
        ]
    },
    {
        "id": 44,
        "brand": "Toyota",
        "model": "Urban Cruiser Hyryder",
        "year": 2024,
        "variant": "V Hybrid",
        "formatted_price": "₹19.99 Lakh",
        "emi": "₹41,800",
        "mileage": "27.97 kmpl",
        "fuel_type": "Hybrid",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1490 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/urban-cruiser-hyryder/1.jpeg",
            "assets/images/urban-cruiser-hyryder/2.jpeg",
            "assets/images/urban-cruiser-hyryder/3.jpeg",
            "assets/images/urban-cruiser-hyryder/4.jpeg"
        ]
    },
    {
        "id": 45,
        "brand": "Toyota",
        "model": "Innova Hycross",
        "year": 2024,
        "variant": "ZX (O) Hybrid",
        "formatted_price": "₹30.98 Lakh",
        "emi": "₹64,700",
        "mileage": "23.24 kmpl",
        "fuel_type": "Hybrid",
        "transmission": "Automatic",
        "body_type": "MUV",
        "engine": "1987 cc",
        "seating_capacity": 7,
        "seats": 7,
        "featured": true,
        "images": [
            "assets/images/innova-hycross/1.png",
            "assets/images/innova-hycross/2.png",
            "assets/images/innova-hycross/3.jpeg",
            "assets/images/innova-hycross/4.jpeg"
        ]
    },
    {
        "id": 46,
        "brand": "Volkswagen",
        "model": "Virtus",
        "year": 2024,
        "variant": "GT Plus Edge",
        "formatted_price": "₹19.41 Lakh",
        "emi": "₹40,600",
        "mileage": "18.67 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Sedan",
        "engine": "1498 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/virtus/1.png",
            "assets/images/virtus/2.png",
            "assets/images/virtus/3.png",
            "assets/images/virtus/4.jpeg"
        ]
    },
    {
        "id": 47,
        "brand": "Volkswagen",
        "model": "Taigun",
        "year": 2024,
        "variant": "GT Plus Edge",
        "formatted_price": "₹19.46 Lakh",
        "emi": "₹40,700",
        "mileage": "18.15 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "SUV",
        "engine": "1498 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/taigun/1.jpeg",
            "assets/images/taigun/2.jpeg",
            "assets/images/taigun/3.jpeg",
            "assets/images/taigun/4.jpeg"
        ]
    },
    {
        "id": 48,
        "brand": "BMW",
        "model": "3 Series Gran Limousine",
        "year": 2024,
        "variant": "330Li M Sport",
        "formatted_price": "₹60.60 Lakh",
        "emi": "₹1,26,700",
        "mileage": "15.39 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Sedan",
        "engine": "1998 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": true,
        "images": [
            "assets/images/3-series-gran-limousine/1.jpeg",
            "assets/images/3-series-gran-limousine/2.jpeg",
            "assets/images/3-series-gran-limousine/3.jpeg",
            "assets/images/3-series-gran-limousine/4.jpeg"
        ]
    },
    {
        "id": 49,
        "brand": "Audi",
        "model": "A4",
        "year": 2024,
        "variant": "Technology",
        "formatted_price": "₹53.50 Lakh",
        "emi": "₹1,11,800",
        "mileage": "17.4 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Sedan",
        "engine": "1998 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": false,
        "images": [
            "assets/images/a4/1.png",
            "assets/images/a4/2.png",
            "assets/images/a4/3.jpeg",
            "assets/images/a4/4.jpeg"
        ]
    },
    {
        "id": 50,
        "brand": "Mercedes-Benz",
        "model": "C-Class",
        "year": 2024,
        "variant": "C 300 AMG Line",
        "formatted_price": "₹62.70 Lakh",
        "emi": "₹1,31,000",
        "mileage": "17.5 kmpl",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "body_type": "Sedan",
        "engine": "1999 cc",
        "seating_capacity": 5,
        "seats": 5,
        "featured": true,
        "images": [
            "assets/images/c-class/1.png",
            "assets/images/c-class/2.png",
            "assets/images/c-class/3.jpeg",
            "assets/images/c-class/4.jpeg"
        ]
    }
];
